---
title: "Working group schedule"
output:
  pdf_document: default
---

## Working group schedule:

+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Day     | Time    | Activity                                                                                                          | Notes for planning                                                                                      |
+=========+=========+===================================================================================================================+=========================================================================================================+
| **Mon** | 8am     | Breakfast                                                                                                         |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9am     | Welcome and icebreaker                                                                                            |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9.30am  | Lecture: Introduction to the Straight of Georgia food web. *Brian Hunt*                                           | 60 min with time for Questions                                                                          |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 10.30am | Revisiting the overall aim of the week, and the schedule.                                                         | 30 min.                                                                                                 |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 11am    | Presentation of pre-working group assignments                                                                     | 3-5 min per participant: *How are trait-based approaches used in your general field of study?*          |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 12pm    | Lunch                                                                                                             |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 1pm     | Lecture: Zooplankton traits. *Patrick Pata*                                                                       |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 2pm     | Coffee and group activity: From taxonomy to functional ecology                                                    | Breakout groups to discuss:\                                                                            |
|         |         |                                                                                                                   | Compile a list of questions to report back:\                                                            |
|         |         |                                                                                                                   | a. Are current trait frameworks sufficient?\                                                            |
|         |         |                                                                                                                   | b. What information is needed?\                                                                         |
|         |         |                                                                                                                   | c. Which ecosystem functions do traits correspond to?\                                                  |
|         |         |                                                                                                                   | d. What ecosystem services can traits affect?\                                                          |
|         |         |                                                                                                                   | e. which traits are important for specific ecosystem functions?                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 3.30pm  | Discussion: Research questions and topics.                                                                        | Aim: Produce a list of research hypotheses on the whiteboard.                                           |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 5pm     | Dinner and get together                                                                                           |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         |         |                                                                                                                   |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| **Tue** | 8am     | Breakfast                                                                                                         |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9am     | Workshop: Revisit the structure of datasets.                                                                      |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 10.30am | Guest lecture: What is needed to assess the health of the pacific salmon population? *Pacific Salmon Foundation.* | Including q&a session.                                                                                  |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 12pm    | Lunch with guest speaker                                                                                          |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 1pm     | Discussion: Revisit the hypotheses of the workshop.                                                               | 1\. Group discussion - questions arising from the lecture. 30 min\                                      |
|         |         |                                                                                                                   | 2. Breakout groups - reviewing the list of hypotheses from Monday. 60 min.\                             |
|         |         |                                                                                                                   | Coffee\                                                                                                 |
|         |         |                                                                                                                   | 3. Whole group presentation: peer review discussion, update the whiteboard list of hypotheses. 60 min.\ |
|         |         |                                                                                                                   | 4. Sign up to project focus groups. 30 min.                                                             |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 4pm     | Work in focus groups.                                                                                             | Groups develop to present on Wednesday morning.                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 6pm     | Dinner                                                                                                            |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         |         |                                                                                                                   |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| **Wed** | 8am     | Breakfast                                                                                                         |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9am     | Lecture: From feeding trait to ecosystem function. *Andreas Novotny*                                              |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9.45am  | Presentation of work plan and procedures, and feedback.                                                           |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 11am    | Work in focus groups                                                                                              |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 12pm    | Lunch                                                                                                             |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 1pm     | Work in focus groups                                                                                              |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 5pm     | Updates for the day                                                                                               |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 6pm     | Dinner                                                                                                            |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         |         |                                                                                                                   |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| **Thu** | 8am     | Breakfast                                                                                                         |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9am     | Progress presentations and feedback                                                                               |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 11am    | Guest lecture: Howe sound biosphere region.                                                                       |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 12pm    | Lunch                                                                                                             |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 1pm     | Reflections on presentation                                                                                       |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 1.30pm  | Work in focus groups                                                                                              |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 5pm     | Updates for the day                                                                                               |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 6pm     | Dinner                                                                                                            |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         |         |                                                                                                                   |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Fri     | 8am     | Breakfast                                                                                                         |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 9am     | Final presentations with peer feedback.                                                                           |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 11am    | Concluding discussion.                                                                                            | Final discussion of main conclusion, how to split future work and potential publications.\              |
|         |         |                                                                                                                   | Feed back.\                                                                                             |
|         |         |                                                                                                                   | Authorship policy.                                                                                      |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
|         | 12pm    | Lunch and travel home                                                                                             |                                                                                                         |
+---------+---------+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
